services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      UPLOAD_LIMIT: 256M
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "127.0.0.1:8083:80"

volumes:
  mysql_data:
